### ISSUE TITLE
文中提供的MIDAS数据集的链接失效，已无法下载

### ISSUE THREAD

**Issue by y8421036** [iMED-Lab/CS-Net#2]
您好！在MIA上的CS-Net中的3D网络在3个数据集上进行评估，但是文中提供的MIDAS数据集的链接已失效，不能下载数据，请问是否可以提供新的链接，或者通过其他方式共享一下数据集。
刚刚接触血管分割方向，一直没有数据集，希望您可以帮助一下，非常感激！

**Comment by moulei1234** [comment]
http://insight-journal.org/midas/community/view/21

**Comment by y8421036** [comment]
> http://insight-journal.org/midas/community/view/21

您好，我在这个网站找了好久，请问是不是没有脑血管的label呀？可以提供一下标签吗？谢谢啦

**Comment by moulei1234** [comment]
> > http://insight-journal.org/midas/community/view/21
> 
> 您好，我在这个网站找了好久，请问是不是没有脑血管的label呀？可以提供一下标签吗？谢谢啦

The labels for MIDAS are not currently publicly available.

**Comment by y8421036** [comment]
> > > http://insight-journal.org/midas/community/view/21
> > 
> > 
> > 您好，我在这个网站找了好久，请问是不是没有脑血管的label呀？可以提供一下标签吗？谢谢啦
> 
> The labels for MIDAS are not currently publicly available.

好的，谢谢您的回复。

**Comment by moulei1234** [comment]
> > > > http://insight-journal.org/midas/community/view/21
> > > 
> > > 
> > > 您好，我在这个网站找了好久，请问是不是没有脑血管的label呀？可以提供一下标签吗？谢谢啦
> > 
> > 
> > The labels for MIDAS are not currently publicly available.
> 
> 好的，谢谢您的回复。

Although the MIDAS labels used in our paper are not publicly available, [HERE](https://public.kitware.com/Wiki/TubeTK/Data) is an alternative that is publicly available. It's worth noting that the labels provided in [HERE](https://public.kitware.com/Wiki/TubeTK/Data) are stored in ```.tre``` format, and you need to expand a bit of effort converting them into a format that satisfies you. 
BTW, If you are having trouble converting ```.tre```, the reference provided [here](https://discourse.itk.org/t/how-to-open-tre-file/2538) may help you.

Hope this information is useful to you, Gook Luck!

**Comment by moulei1234** [comment]
> > > > http://insight-journal.org/midas/community/view/21
> > > 
> > > 
> > > 您好，我在这个网站找了好久，请问是不是没有脑血管的label呀？可以提供一下标签吗？谢谢啦
> > 
> > 
> > The labels for MIDAS are not currently publicly available.
> 
> 好的，谢谢您的回复。

Although the MIDAS labels used in our paper are not publicly available, [HERE](https://public.kitware.com/Wiki/TubeTK/Data) is an alternative that is publicly available. It's worth noting that the labels provided in [HERE](https://public.kitware.com/Wiki/TubeTK/Data) are stored in ```.tre``` format, and you need to expand a bit of effort converting them into a format that satisfies you. 
BTW, If you are having trouble converting ```.tre```, the reference provided [here](https://discourse.itk.org/t/how-to-open-tre-file/2538) may help you.

Hope this information is useful to you, Gook Luck!

**Comment by y8421036** [comment]
> > > > > http://insight-journal.org/midas/community/view/21
> > > > 
> > > > 
> > > > 您好，我在这个网站找了好久，请问是不是没有脑血管的label呀？可以提供一下标签吗？谢谢啦
> > > 
> > > 
> > > The labels for MIDAS are not currently publicly available.
> > 
> > 
> > 好的，谢谢您的回复。
> 
> Although the MIDAS labels used in our paper are not publicly available, [HERE](https://public.kitware.com/Wiki/TubeTK/Data) is an alternative that is publicly available. It's worth noting that the labels provided [HERE](https://public.kitware.com/Wiki/TubeTK/Data) are stored in `.tre` format, and you need to expand a bit of effort converting them into a format that satisfies you. BTW, If you are having trouble converting `.tre`, the reference provided [here](https://discourse.itk.org/t/how-to-open-tre-file/2538) may help you.
> 
> Hope this information is useful to you, Good Luck!

谢谢您的帮助，我学习一下.tre的转换

**Comment by beibei5898** [comment]
不好意思，打扰您一下，上面这个网页链接又失效了，能再发一下吗？谢谢

**Comment by iBrain-007** [comment]
> 不好意思，打扰您一下，上面这个网页链接又失效了，能再发一下吗？谢谢

Hi, @beibei5898 

I'm surprised to find that I can't open the link above either, sorry about that!
Maybe you can find the download link from: https://public.kitware.com/Wiki/TubeTK/Data

Best,
Brain
